---
language: python
python: 3.6

cache: pip

env:
  global:
    - DJANGO_SECRET_KEY=test

install:
  - pip install --upgrade pipenv
  - pipenv sync --dev

script:
  - pipenv run flake8
  - pipenv run coverage run -m pytest timetracker/

after_success: pipenv run codecov

notifications:
  email:
    on_failure: always
    on_success: never
