---
language: python
python: 3.6

cache: pip

env:
  global:
    - DJANGO_SECRET_KEY=test

install:
  - pip install --upgrade pipenv
  - pipenv install --dev

script:
  - pipenv run flake8
  - pipenv run pytest timetracker/

notifications:
  email:
    on_failure: always
    on_success: never
