---
language: python
python: 3.6

cache: pip

install:
  - pip install --upgrade pip==18.0
  - pip install pipenv
  - pipenv install pip==18.0
  - pipenv install --dev

script: pipenv run flake8

notifications:
  email:
    on_failure: always
    on_success: never
