# Generated by Django 2.1.2 on 2018-10-12 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vms', '0001_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffingAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The primary email address for the agency.', max_length=254, verbose_name='primary email address')),
                ('name', models.CharField(help_text='The name of the staffing agency.', max_length=100, verbose_name='name')),
                ('notes', models.TextField(blank=True, help_text='Additional information about the staffing agency.', verbose_name='notes')),
                ('phone_number', models.CharField(blank=True, help_text='The phone number that the agency can be reached at.', max_length=30, verbose_name='phone number')),
                ('slug', models.SlugField(help_text='The URL slug used to look up the staffing agency.', max_length=57, verbose_name='slug')),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='The time the agency was created.', verbose_name='creation time')),
                ('time_updated', models.DateTimeField(auto_now=True, help_text="The last time the agency's information was updated.", verbose_name='last update time')),
            ],
            options={
                'verbose_name': 'staffing agency',
                'verbose_name_plural': 'staffing agencies',
                'ordering': ('name', 'time_created'),
            },
        ),
        migrations.CreateModel(
            name='StaffingAgencyAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='The time the admin was created at.', verbose_name='creation time')),
                ('agency', models.ForeignKey(help_text='The staffing agency that the user has admin rights to.', on_delete=django.db.models.deletion.CASCADE, related_name='admins', related_query_name='admin', to='vms.StaffingAgency', verbose_name='staffing agency')),
                ('user', models.ForeignKey(help_text='The user who has admin rights on the linked agency.', on_delete=django.db.models.deletion.CASCADE, related_name='agency_admins', related_query_name='agency_admin', to=settings.AUTH_USER_MODEL, verbose_name='admin user')),
            ],
            options={
                'verbose_name': 'staffing agency administrator',
                'verbose_name_plural': 'staffing agency administrators',
                'ordering': ('agency__name', 'user__name', 'time_created'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='staffingagencyadmin',
            unique_together={('agency', 'user')},
        ),
    ]
