# Generated by Django 2.1.2 on 2018-10-11 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vms', '0002_timerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRecordApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='A unique identifier for the approval record.', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('time_approved', models.DateTimeField(auto_now_add=True, help_text='The time that the associated time record was approved.', verbose_name='approval time')),
            ],
            options={
                'verbose_name': 'time record approval',
                'verbose_name_plural': 'time record approvals',
                'ordering': ('time_approved',),
            },
        ),
        migrations.RemoveField(
            model_name='timerecord',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='timerecordapproval',
            name='time_record',
            field=models.OneToOneField(help_text='The time record that is being approved.', on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='vms.TimeRecord', verbose_name='time record'),
        ),
        migrations.AddField(
            model_name='timerecordapproval',
            name='user',
            field=models.ForeignKey(help_text='The user who approved the time record.', on_delete=django.db.models.deletion.CASCADE, related_name='time_record_approvals', related_query_name='time_record_approval', to=settings.AUTH_USER_MODEL, verbose_name='approving user'),
        ),
    ]
