# Generated by Django 2.1.2 on 2018-10-12 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='More details about the job.', verbose_name='description')),
                ('name', models.CharField(help_text='The name of the job', max_length=100, verbose_name='name')),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=11)),
                ('slug', models.SlugField(help_text='A unique slug that can be used to retrieve the job.', max_length=100, verbose_name='slug')),
                ('client', models.ForeignKey(help_text='The client that the job is performed for.', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', related_query_name='job', to='vms.Client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'client job',
                'verbose_name_plural': 'client jobs',
                'ordering': ('name',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='clientjob',
            unique_together={('client', 'slug')},
        ),
    ]
