# Generated by Django 2.1.2 on 2018-10-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0003_timerecordapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The primary email address for the client.', max_length=254, verbose_name='primary email address')),
                ('name', models.CharField(help_text='The name of the client company.', max_length=100, verbose_name='name')),
                ('notes', models.TextField(blank=True, help_text='Additional information about the client.', verbose_name='notes')),
                ('phone_number', models.CharField(blank=True, help_text='The phone number that the client can be reached at.', max_length=30, verbose_name='phone number')),
                ('slug', models.SlugField(help_text='The URL slug used to look up the client.', max_length=57, verbose_name='slug')),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='The time the client was created.', verbose_name='creation time')),
                ('time_updated', models.DateTimeField(auto_now=True, help_text="The last time the client's information was updated.", verbose_name='last update time')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ('name', 'time_created'),
            },
        ),
    ]
