# Generated by Django 2.1.2 on 2018-10-12 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vms', '0004_clientjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='A unique identifier for the time record.', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('time_end', models.DateTimeField(blank=True, help_text='The ending time of the work period.', null=True, verbose_name='end time')),
                ('time_start', models.DateTimeField(default=django.utils.timezone.now, help_text='The start time of the work period.', verbose_name='start time')),
                ('employee', models.ForeignKey(help_text='The employee who worked during this time period.', on_delete=django.db.models.deletion.CASCADE, related_name='time_records', related_query_name='time_record', to='vms.Employee', verbose_name='employee')),
                ('job', models.ForeignKey(help_text='The job type that the employee worked on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_records', related_query_name='time_record', to='vms.ClientJob', verbose_name='client job')),
            ],
            options={
                'verbose_name': 'time record',
                'verbose_name_plural': 'time records',
                'ordering': ('time_start',),
            },
        ),
        migrations.CreateModel(
            name='TimeRecordApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='A unique identifier for the approval record.', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('time_approved', models.DateTimeField(auto_now_add=True, help_text='The time that the associated time record was approved.', verbose_name='approval time')),
                ('time_record', models.OneToOneField(help_text='The time record that is being approved.', on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='vms.TimeRecord', verbose_name='time record')),
                ('user', models.ForeignKey(help_text='The user who approved the time record.', on_delete=django.db.models.deletion.CASCADE, related_name='time_record_approvals', related_query_name='time_record_approval', to=settings.AUTH_USER_MODEL, verbose_name='approving user')),
            ],
            options={
                'verbose_name': 'time record approval',
                'verbose_name_plural': 'time record approvals',
                'ordering': ('time_approved',),
            },
        ),
    ]
