# Generated by Django 2.1.2 on 2018-10-23 19:47

from django.db import migrations, models


def fill_in_employee_ids(apps, schema_editor):
    """
    Default to the employee's primary key as their employee ID.
    """
    Employee = apps.get_model('vms', 'Employee')
    for emp in Employee.objects.all():
        emp.employee_id = emp.id
        emp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0005_timerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='A unique number identifying the employee within the client company they work for.', null=True, verbose_name='employee ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='A boolean indicating if this user is currently active. Inactive employees cannot log any working hours.', verbose_name='is active'),
        ),

        # Fill in blank employee IDs
        migrations.RunPython(fill_in_employee_ids, migrations.RunPython.noop),

        # We can drop the 'nullable' attribute because we filled in the
        # missing employee IDs.
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='A unique number identifying the employee within the client company they work for.', verbose_name='employee ID'),
        ),
    ]
