# Generated by Django 2.1.2 on 2018-10-12 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0005_clientadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffingAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the staffing agency.', max_length=100, verbose_name='name')),
                ('notes', models.TextField(blank=True, help_text='Additional information about the staffing agency.', verbose_name='notes')),
                ('phone_number', models.CharField(blank=True, help_text='The phone number that the agency can be reached at.', max_length=30, verbose_name='phone number')),
                ('slug', models.SlugField(help_text='The URL slug used to look up the staffing agency.', max_length=57, verbose_name='slug')),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='The time the agency was created.', verbose_name='creation time')),
                ('time_updated', models.DateTimeField(auto_now=True, help_text="The last time the agency's information was updated.", verbose_name='last update time')),
                ('email', models.EmailField(help_text='The primary email address for the agency.', max_length=254, verbose_name='primary email address')),
            ],
            options={
                'verbose_name': 'staffing agency',
                'verbose_name_plural': 'staffing agencies',
                'ordering': ('name', 'time_created'),
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.AddField(
            model_name='employee',
            name='staffing_agency',
            field=models.ForeignKey(help_text='The staffing agency that hired the employee.', on_delete=django.db.models.deletion.CASCADE, related_name='employees', related_query_name='employee', to='vms.StaffingAgency', verbose_name='staffing agency'),
        ),
    ]
