# Generated by Django 2.1.2 on 2018-10-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0006_employeeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='A unique numeric identifier for the client. If not specified, it will be randomly generated.', primary_key=True, serialize=False, unique=True, verbose_name='client ID'),
        ),
    ]
