# Generated by Django 2.1.2 on 2018-10-24 22:41

from django.db import migrations, models
import django.db.models.deletion


def add_clients(apps, schema_editor):
    """
    Use each employee's supervisor to assign their client company.
    """
    Employee = apps.get_model('vms', 'Employee')
    for emp in Employee.objects.all():
        emp.client = emp.supervisor.client
        emp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0007_clientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='client',
            field=models.ForeignKey(help_text='The client company the employee works for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', related_query_name='employee', to='vms.Client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text="The client administrator who can approve the user's hours.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', related_query_name='employee', to='vms.ClientAdmin', verbose_name='supervisor'),
        ),

        # Fill in client information
        migrations.RunPython(add_clients, migrations.RunPython.noop),

        # Alter field to be non-nullable since we've handled the nulls
        migrations.AlterField(
            model_name='employee',
            name='client',
            field=models.ForeignKey(help_text='The client company the employee works for.', on_delete=django.db.models.deletion.CASCADE, related_name='employees', related_query_name='employee', to='vms.Client', verbose_name='client'),
        ),
    ]
