# Generated by Django 2.1.2 on 2018-10-27 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vms', '0008_employee_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffingAgencyEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='A unique identifier for the employee.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, help_text='A boolean indicating if the employee has been accepted into the agency.', verbose_name='is approved')),
                ('time_approved', models.DateTimeField(blank=True, help_text='The time that the request was approved.', null=True, verbose_name='approval time')),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='The time that the request was submitted.', verbose_name='creation time')),
                ('agency', models.ForeignKey(help_text='The staffing agency the employee works for.', on_delete=django.db.models.deletion.CASCADE, related_name='employees', related_query_name='employee', to='vms.StaffingAgency', verbose_name='staffing agency')),
                ('approved_by', models.ForeignKey(blank=True, help_text='The admin who accepted the employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_employees', to='vms.StaffingAgencyAdmin')),
                ('user', models.ForeignKey(help_text='The user that works for the agency.', on_delete=django.db.models.deletion.CASCADE, related_name='staffing_agency_employees', related_query_name='staffing_agency_employee', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'staffing agency employee',
                'verbose_name_plural': 'staffing agency employees',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='staffing_agency',
            field=models.ForeignKey(help_text='The staffing agency that hired the employee.', on_delete=django.db.models.deletion.CASCADE, related_name='client_employees', related_query_name='client_employee', to='vms.StaffingAgency', verbose_name='staffing agency'),
        ),
        migrations.AlterUniqueTogether(
            name='staffingagencyemployee',
            unique_together={('agency', 'user')},
        ),
    ]
