# Generated by Django 2.1.2 on 2018-10-31 19:00

from django.db import migrations, models


def migrate_pay_rates(apps, schema_editor):
    """
    Fill in pay rates for existing time records.
    """
    TimeRecord = apps.get_model('vms', 'TimeRecord')
    for record in TimeRecord.objects.all():
        record.pay_rate = record.job.pay_rate if record.job else 0
        record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0009_staffingagencyemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, help_text='The hourly pay for the time record.', max_digits=11, null=True, verbose_name='pay rate'),
        ),

        migrations.RunPython(migrate_pay_rates, migrations.RunPython.noop),

        migrations.AlterField(
            model_name='timerecord',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, help_text='The hourly pay for the time record.', max_digits=11, verbose_name='pay rate'),
        ),
    ]
