# Generated by Django 2.1.2 on 2018-11-01 16:25

from django.db import migrations, models
import django.db.models.deletion


def default_approvals(apps, schema_editor):
    """
    Fill in default information for existing employee approval
    information.
    """
    Employee = apps.get_model('vms', 'Employee')
    for employee in Employee.objects.all():
        employee.approved_by = employee.supervisor
        employee.time_approved = employee.time_created
        employee.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0010_timerecord_pay_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='The admin who approved the employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_employees', related_query_name='approved_employee', to='vms.ClientAdmin', verbose_name='approved by'),
        ),
        migrations.AddField(
            model_name='employee',
            name='time_approved',
            field=models.DateTimeField(blank=True, help_text='The time that the employee was approved.', null=True, verbose_name='approval time'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=False, help_text='A boolean indicating if this user is currently active. Inactive employees cannot log any working hours.', verbose_name='is active'),
        ),
        migrations.RunPython(default_approvals, migrations.RunPython.noop),
    ]
