# Generated by Django 2.1.2 on 2018-11-12 16:37

from django.db import migrations, models
import django.db.models.deletion
import vms.models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0011_employee_approval_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAdminInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The email address to send the invitation to.', max_length=254, verbose_name='email')),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='The time the invitation was created at.', verbose_name='creation time')),
                ('token', models.CharField(blank=True, default=vms.models.generate_token, help_text='A unique token used to accept the invitation.', max_length=16, unique=True, verbose_name='token')),
                ('client', models.ForeignKey(help_text='The client that the invitee will become an admin of.', on_delete=django.db.models.deletion.CASCADE, related_name='admin_invites', related_query_name='admin_invite', to='vms.Client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'client administrator invitation',
                'verbose_name_plural': 'client administrator invitations',
                'ordering': ('time_created',),
            },
        ),
    ]
