# Generated by Django 2.1.2 on 2018-10-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='America/New_York', help_text="The user's timezone.", max_length=32),
        ),
    ]
